# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "my-terraform-state-bucket-danielle"
    dynamodb_table = "terraform-lock-danielle"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "us-east-1"
  }
}
