# RUN

on:
    workflow_call:
        inputs:
            TERRAFORM_VERSION:
                description: "Terraform version to be installed on the runner"
                required: true 
                type: string 
            TERRAGRUNT_VERSION:
                description: "Terragrunt version to be installed on the runner"
                required: true 
                type: string 
            TERRAFORM_WORKING_DIR:     
                description: "Path to the terraform configuration"
                required: true 
                type: string  
            AWS_REGION:
                required: true
                type: string    
                
jobs:
    plan:
        name: 'Terragrunt Init, Validate and Plan'
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-24.04
        defaults:
            run:
              working-directory: ${{inputs.TERRAFORM_WORKING_DIR}}     
        steps:
          - name : "Checkout"
            uses: actions/checkout@v4
            with:
               ref: ${{github.event.pull_request.head.ref}}
          - name: Install Terraform
            uses: hashicorp/setup-terraform@v3
            with:
               terraform_version: ${{ inputs.TERRAFORM_VERSION }}
               terraform_wrapper: true
          - name: Install Terragrunt
            uses: autero1/action-terragrunt@v3
            with:
              terragrunt-version: ${{ inputs.TERRAGRUNT_VERSION }}
          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: us-east-2
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
          
          - name: Terragrunt init
            id: init
            run: terragrunt run-all init -no-color --terragrunt-non-interactive
    
          - name: terragrunt validate
            id: validate
            run: terragrunt run-all validate -no-color --terragrunt-non-interactive
          
          - name: terragrunt plan
            id: plan
            run: terragrunt run-all plan-no-color --terragrunt-non-interactive
            continue-on-error: true
    
    